### ISSUE TITLE
工作量统计

### ISSUE THREAD

**Issue by o0Roy** [TaibiaoGuo/blockchainTutorial#178]
**任务标题**：
工作量统计
**任务描述**：
对issue及工作量进行统计

|姓名 | 解决issue数量 | 工作总量|
|-- | :--: | :--:|
|黄松强 | 15 | 34|
|闫月 | 21 | 53.5|
|吴俊 | 25 | 52.5|
|陈不凡 | 1 | 6|
|龚思远 | 1 | 6|

**Comment by TaibiaoGuo** [comment]
后续工作中，帮助其他同事也可以算工作量。
